### ISSUE TITLE
File to import not found or unreadable: ../../../search/scss/index

### ISSUE THREAD

**Issue by FuadEfendi** [hbstack/search#209] opened 2024-06-14 01:25 UTC
See this:

https://github.com/hbstack/search/blob/0ca1dd40726bbc72b907c80d4f28d2c40f40e0e9/assets/hb/modules/search/index.scss#L2

```
@import "../../../search/scss/index";

```

It imports non-existing file?

I have this trying to build:
```
ERROR TOCSS: failed to transform "/hb/modules/search/index.scss" (text/x-scss): "/Users/fefendi/Library/Caches/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hbstack/search@v0.2.2/assets/hb/modules/search/index.scss:2:1": File to import not found or unreadable: /Users/fefendi/Library/Caches/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugomods/search@v0.14.0/assets/search/scss/index.scss.
```

Maybe I need command to install "hugomods/search"? So strange, it started to happen after few upgrades

**Comment by razonyang** [comment] 2024-06-14 04:25
This module already declare it's deps on https://github.com/hbstack/search/blob/0ca1dd40726bbc72b907c80d4f28d2c40f40e0e9/hugo.toml#L2, you won't need to  import `hugomods/search` module explicitly.

The related module is broken, perhaps search module was'nt downloaded complete, use the following command to check if the file exist.

```sh
cat /Users/fefendi/Library/Caches/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugomods/search@v0.14.0/assets/search/scss/index.scss
```

Perhaps there is potential bug, but I couldnt reproduce, please provide reproduce steps if the file exist.

**Comment by razonyang** [comment] 2024-06-14 13:40
> It could be specific for SCSS compiler Mac version

It is indeed possible, you can verify this by using [hugomods/hugo:exts](https://docker.hugomods.com/docs/development/docker-run/) Docker image if you have Docker installed.

```sh
cd /path/to/your-site

docker run \
  -v $PWD:/src \
  -v /Users/fefendi/Library/Caches/hugo_cache:/tmp/hugo_cache \
  hugomods/hugo:exts \
  hugo server --bind 0.0.0.0
```

> Please note that there may be permission issue when files changed inside the container (default run as root), such as download modules, hugo stats and lock file.

I'm using `github.com/sass/libsass="3.6.5"` without problem.

**Comment by razonyang** [comment] 2024-08-14 04:46
Seems duplicate to https://github.com/orgs/hbstack/discussions/68, closing for now.

**Closed by razonyang** 2024-08-14 04:46 UTC
